AWSTemplateFormatVersion: 2010-09-09
Description: ECS (Fargate) cluster
Parameters:
  ECSClusterName:
    Type: String
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties: 
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT