AWSTemplateFormatVersion: 2010-09-09
Description: Log group for an ECS Task Definition
Parameters:
  TaskDefinitionName:
    Type: String
Resources:
  MyLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: 
        Fn::Sub: /ecs/${TaskDefinitionName}